import auto from 'eslint-config-canonical/auto';
import { recommended as jsxA11y } from 'eslint-config-canonical/jsx-a11y';
import { recommended as vitest } from 'eslint-config-canonical/vitest';
import { createTypeScriptImportResolver } from 'eslint-import-resolver-typescript';
import { defineConfig, globalIgnores } from 'eslint/config';

export default defineConfig(
  globalIgnores([
    'coverage',
    'dist',
    // Generated by the Better Auth CLI into src/db/auth-schema.ts
    'src/db/auth-schema.ts',
    // Generated by drizzle-kit (migration SQL and JSON snapshots)
    'drizzle',
    'node_modules',
    '.wrangler',
    '**/pnpm-lock.yaml',
    '.release',
    '**/.leadscroll',
  ]),
  ...auto,
  {
    // The public SDK is plain browser JavaScript without a build step.
    files: ['public/**/*.js'],
    languageOptions: {
      globals: {
        console: 'readonly',
        CustomEvent: 'readonly',
        document: 'readonly',
        fetch: 'readonly',
        FormData: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        URL: 'readonly',
        window: 'readonly',
      },
    },
    rules: {
      // The SDK's collection warnings are its only diagnostics channel.
      'no-console': 0,
    },
  },
  {
    // The test file drives a real browser: page.evaluate callbacks and the
    // fixture assertions run against DOM globals, while the harness itself is
    // Node.
    files: ['scripts/source/sdk.mjs'],
    languageOptions: {
      globals: {
        document: 'readonly',
        Event: 'readonly',
        window: 'readonly',
      },
    },
  },
  {
    // Use import-x's modern resolver API: the legacy "node" resolver fallback
    // resolves <packageDir>/node, which under pnpm loads a dependency package's
    // node/ subdirectory (e.g. lightningcss) and crashes import/no-cycle
    settings: {
      'import-x/resolver-next': [createTypeScriptImportResolver()],
    },
  },
  // canonical's vitest ruleset, scoped to the test files so it does not leak into src
  ...vitest.map((config) => ({ ...config, files: ['tests/**/*.test.ts'] })),
  // canonical's jsx-a11y ruleset, scoped to the TSX files so it does not leak into .ts
  ...jsxA11y.map((config) => ({ ...config, files: ['**/*.tsx'] })),
  {
    files: ['**/*.{ts,tsx}'],
    rules: {
      // Project convention is kebab-case modules, PascalCase components, and *.test.ts;
      // canonical disables this rule in its own root config for the same reason
      'canonical/filename-match-regex': 0,
      // Env is the Cloudflare Workers convention for the environment binding type;
      // renaming it would ripple through the whole Worker contract
      'unicorn/prevent-abbreviations': [
        'error',
        {
          allowList: { Env: true },
        },
      ],
    },
  },
  {
    files: ['tests/auth.test.ts'],
    rules: {
      // expectUnauthorized is a local assertion helper that wraps expect()
      'vitest/expect-expect': [
        'error',
        {
          assertFunctionNames: ['assert', 'expect', 'expectUnauthorized'],
        },
      ],
    },
  },
  {
    files: ['**/*.tsx'],
    rules: {
      // Tailwind classes are passed through className and dnd-kit sets style directly,
      // so the props canonical forbids are the normal styling mechanism here
      'react/forbid-component-props': ['error', { forbid: [] }],
    },
  },
  {
    files: ['src/api/logging.ts'],
    rules: {
      // Structured JSON lines on Worker stdout are this module's only purpose
      'no-console': 0,
    },
  },
  {
    files: ['src/main.tsx'],
    rules: {
      // Side-effect import of the Tailwind stylesheet
      'import/no-unassigned-import': 0,
    },
  },
  {
    // Database port boundary: only src/db/driver.ts may import the engine's
    // Drizzle driver or name the runtime binding types. A second engine means
    // a second adapter module, not edits across the application.
    files: ['src/**/*.{ts,tsx}'],
    ignores: ['src/db/driver.ts'],
    rules: {
      '@typescript-eslint/no-restricted-types': [
        'error',
        {
          types: {
            D1Database: {
              fixWith: 'Database',
              message: 'Use { type Database } from @/db/driver.',
            },
            D1PreparedStatement: {
              fixWith: 'Statement',
              message: 'Use { type Statement } from @/db/driver.',
            },
          },
        },
      ],
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              message: 'Import the database port from @/db/driver instead.',
              name: 'drizzle-orm/d1',
            },
          ],
        },
      ],
    },
  },
);
