import auto from 'eslint-config-canonical/auto';
import { recommended as jsxA11y } from 'eslint-config-canonical/jsx-a11y';
import { recommended as vitest } from 'eslint-config-canonical/vitest';
import { createTypeScriptImportResolver } from 'eslint-import-resolver-typescript';
import { defineConfig, globalIgnores } from 'eslint/config';

export default defineConfig(
  globalIgnores([
    'coverage',
    'dist',
    // Generated by the Better Auth CLI into src/db/auth-schema.ts
    'src/db/auth-schema.ts',
    // Generated by drizzle-kit (migration SQL and JSON snapshots)
    'drizzle',
    'node_modules',
    '.wrangler',
    'pnpm-lock.yaml',
  ]),
  ...auto,
  {
    // Use import-x's modern resolver API: the legacy "node" resolver fallback
    // resolves <packageDir>/node, which under pnpm loads a dependency package's
    // node/ subdirectory (e.g. lightningcss) and crashes import/no-cycle
    settings: {
      'import-x/resolver-next': [createTypeScriptImportResolver()],
    },
  },
  // canonical's vitest ruleset, scoped to the test files so it does not leak into src
  ...vitest.map((config) => ({ ...config, files: ['tests/**/*.test.ts'] })),
  // canonical's jsx-a11y ruleset, scoped to the TSX files so it does not leak into .ts
  ...jsxA11y.map((config) => ({ ...config, files: ['**/*.tsx'] })),
  {
    files: ['**/*.{ts,tsx}'],
    rules: {
      // Project convention is kebab-case modules, PascalCase components, and *.test.ts;
      // canonical disables this rule in its own root config for the same reason
      'canonical/filename-match-regex': 0,
      // Env is the Cloudflare Workers convention for the environment binding type;
      // renaming it would ripple through the whole Worker contract
      'unicorn/prevent-abbreviations': [
        'error',
        {
          allowList: { Env: true },
        },
      ],
    },
  },
  {
    files: ['tests/auth.test.ts'],
    rules: {
      // expectUnauthorized is a local assertion helper that wraps expect()
      'vitest/expect-expect': [
        'error',
        {
          assertFunctionNames: ['assert', 'expect', 'expectUnauthorized'],
        },
      ],
    },
  },
  {
    files: ['**/*.tsx'],
    rules: {
      // Tailwind classes are passed through className and dnd-kit sets style directly,
      // so the props canonical forbids are the normal styling mechanism here
      'react/forbid-component-props': ['error', { forbid: [] }],
    },
  },
  {
    files: ['src/api/logging.ts'],
    rules: {
      // Structured JSON lines on Worker stdout are this module's only purpose
      'no-console': 0,
    },
  },
  {
    files: ['src/main.tsx'],
    rules: {
      // Side-effect import of the Tailwind stylesheet
      'import/no-unassigned-import': 0,
    },
  },
);
